all:
	mkdir -p assets
	convert ../example/app/controllers/api/.import-graph.svg		assets/app-controllers-api.imports.png
	convert ../example/app/repos/sprints/gorm/.import-graph.svg		assets/app-repos-sprints-gorm.imports.png
	convert ../example/bizrules/usecases/get_sprint/.import-graph.svg	assets/bizrules-usecases-get_sprint.imports.png
	convert ../example/cmd/api/.import-graph.svg				assets/cmd-api.imports.png
